---
title: "Temperature analysis AD ASTRA"
author: "James Watson and Phrutsamon Wongnak"
format: pdf
editor: visual
---

```{r}
knitr::opts_chunk$set(cache = F, cache.comments = FALSE,
                      echo = F, include = TRUE, 
                      fig.width = 8, fig.height = 8,
                      fig.pos = 'H',dev = 'png', dpi = 300)

```

```{r}
library(dplyr)
library(survival)
library(survminer)
library(lubridate)
library(stringr)
library(here)

source("functions.R")
```

## Setup the analysis

```{r}
intervention = 'interim_firstResults'; 
ref_arm = 'No Study Drug'

threshold <- 37
window_clear <- 1
```

## Import data

```{r}
adastra_dat = read.csv(here('Analysis_Data', paste0(intervention,'_analysis.csv')))
adastra_dat <- adastra_dat %>% filter(Timepoint_ID==0) %>% group_by(ID) %>%
  mutate(Baseline_VL = mean(log10_viral_load)) %>%
  distinct(ID, .keep_all = T)

temp_dat <- read.csv(paste0('Analysis_Data/', intervention,'_fever_analysis.csv'))
temp_dat = temp_dat %>% filter(visit != 'D0H1', Time<=7)
temp_dat <- merge(temp_dat, adastra_dat[,c("ID", "Trt",'Baseline_VL')],
                  by.x = "Label", by.y = "ID") 
IDs <- unique(temp_dat$Label)

trts = unique(adastra_dat$Trt)
trts = trts[trts!=ref_arm]
```

```{r}
# temp_dat_for_plot <- temp_dat
# temp_dat_new <- NULL
# 
# for(i in 1:length(IDs)){
#   subdat <- temp_dat_for_plot[temp_dat_for_plot$Label == IDs[i],]
#   if(nrow(subdat) == 0) next
#   
#   subdat$Time_adj <- as.numeric(difftime(subdat$temp_time , min(subdat$temp_time), unit = "days"))
# 
#   subdat <- subdat[order(subdat$Time_adj),]
#   subdat <- subdat %>%
#                    group_by(Timepoint_ID) %>%
#                    mutate("temp_mean" = mean(fut_temp))
#   temp_dat_new <- rbind(temp_dat_new, subdat)
# }
```

## Calculating fever clearance time

```{r}
table(adastra_dat$Fever_Baseline)
table(adastra_dat$Fever_Baseline, adastra_dat$Trt)

# temp_dat_for_plot <- temp_dat_new
temp_dat_for_plot <- cal_fever_clearance(temp_dat, threshold, window_clear)
summary_temp_values = temp_dat_for_plot %>% distinct(Label, .keep_all = T)

# temp_dat_for_plot$Trt <- as.factor(temp_dat_for_plot$Trt)
# temp_dat_for_plot$Trt <- factor(temp_dat_for_plot$Trt, levels = c(ref_arm, trts))
```


individual temperature data
```{r temp_individ_data}
temp_dat_for_plot %>% filter(temp>35) %>% ggplot(aes(x=Time, y = temp, colour = Trt, group = Label))+geom_line(alpha=.3)+geom_smooth(aes(group=Trt), se = F,linewidth = 1.5)+xlab('Time since randomisation (days)')+ylab('Temperature (C)')+theme_bw()
```



```{r}
trt_order <-  c("Baloxavir", "Favipiravir", "Oseltamivir", "No Study Drug")

summary_temp_values <- summary_temp_values %>%
                       mutate(Trt = factor(Trt, levels = trt_order))

fit <- survfit(Surv(clearance_time, clearance_time_cens) ~ Trt, data = summary_temp_values) 
diff=survdiff(Surv(clearance_time, clearance_time_cens) ~ Trt, data = summary_temp_values) 

p_val <- pchisq(diff$chisq, length(diff$n)-1, lower.tail = FALSE)
p_val
```



```{r}
rmean_table <- summary(fit)$table %>% as.data.frame()
rmean_table$strata <- row.names(rmean_table)
rmean_table %>%
  mutate(ci95_up = rmean + 1.96*`se(rmean)`,
         ci95_low = rmean - 1.96*`se(rmean)`,
         lab = paste0(round(rmean,1), " days [95%CI: ", round(ci95_low,1), " to ", round(ci95_up,1), " days]")) %>% select(strata, lab)
```

## Kaplan-Meier plot

```{r}
trt_colors = get_trt_colors()
trt_colors <- trt_colors[!is.na(trt_colors)]
#lab <- c("Baloxavir", "Favipiravir", "Oseltamivir")
cols <- trt_colors[trt_order]
cols <- as.character(cols)
```

```{r fever_clearance}
survplot <- survminer::ggsurvplot(fit,pval=F,
                                  risk.table = T,
                                  risk.table.y.text=F,
                                  palette = cols,
                                  ggtheme = theme_bw(base_size = 16),
                                  legend.labs = trt_order,
                                  break.time.by = 1,
                                  #pval.size = 4,
                                  #pval.coord = c(0,0.1),
                                  size = 1.5,
                                  alpha = 0.7,
                                  xlim = c(0,7)) 
lab <- if (p_val < 1e-3) sprintf("p-value = %.0e", p_val) else sprintf("p-value = %.1f", p_val)

survplot$plot <- survplot$plot + 
  geom_hline(yintercept = c(0,1), linetype = "dashed", linewidth = 0.6) +
  geom_hline(yintercept = 0.5, linetype = "dashed", col = "red", size = 0.6) +
  xlab("Time since randomisation (days)") +
  ylab("Proportion of patients with fever") +
  ggtitle("A) Fever resolution") +
  theme(
        axis.title=element_text(face="bold",),
        strip.text = element_text(face = "bold"),
        title = element_blank()
  ) +
  annotate("text", x = 0, y = 0.1, label = lab, vjust=0, hjust = 0)


survplot
```

```{r}
fname <- paste0(here("Plots", intervention, "Temp_surv_plot.pdf"))

pdf(fname, width = 6, height = 6)
print(survplot, newpage = F)
dev.off()
```

```{r}
# temp_dat_for_plot2

# temp_dat_for_plot2$Trt <- as.factor(temp_dat_for_plot2$Trt)
# temp_dat_for_plot2$Trt <- factor(temp_dat_for_plot2$Trt, levels = c(ref_arm, trts))

# coxfit <- coxph(Surv(clearance_time, clearance_time_cens) ~ Trt, data = temp_dat_for_plot2) 
# print(coxfit)
```

```{r}
# print(data.frame(exp(coxfit$coefficients) , exp(confint(coxfit))))
```

```{r}
#Pair-wise log-rank test against reference arm
pw_logrank_pval <- NULL
for(i in 1:length(trts)){
  trt_i <- trts[i]
  temp <- summary_temp_values %>% filter(Trt %in% c(ref_arm, trt_i))
  diff_i =survdiff(Surv(clearance_time, clearance_time_cens) ~ Trt, data = temp) 
  p_val_i <- pchisq(diff_i$chisq, length(diff_i$n)-1, lower.tail = FALSE)
  
  pw_logrank_pval <- rbind(pw_logrank_pval,
                           data.frame(trt_i, ref_arm, p_val_i))
  
}

pw_logrank_pval

```

```{r}
library(gridExtra)
survplot_fever <- survplot

grob1 <- arrangeGrob(survplot_fever$plot, survplot_fever$table, ncol = 1, heights = c(2, 1))
grob2 <- arrangeGrob(survplot$plot, survplot$table, ncol = 1, heights = c(2, 1))


```

```{r}
fname <- paste0(here("Plots", intervention, "fever_symptom_surv_plot_7days.png"))

png(fname, width = 13, height = 7, unit = 'in', res = 350)
print(ggarrange(grob1, grob2, ncol = 2, nrow = 1))
dev.off()
```